// Code generated by qtc from "chaosType.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:1
package v1alpha1

//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:1
import "github.com/iancoleman/strcase"

//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:3
func StreamChaosType(qw422016 *qt422016.Writer, name string) {
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:3
	qw422016.N().S(`
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// +kubebuilder:object:root=true

// `)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:13
	qw422016.E().V(strcase.ToCamel(name))
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:13
	qw422016.N().S(`Chaos is the Schema for the `)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:13
	qw422016.E().V(strcase.ToCamel(name))
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:13
	qw422016.N().S(`chaos API
type `)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:14
	qw422016.E().V(strcase.ToCamel(name))
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:14
	qw422016.N().S(`Chaos struct {
	metav1.TypeMeta   `)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:14
	qw422016.N().S("`")
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:14
	qw422016.N().S(`json:",inline"`)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:14
	qw422016.N().S("`")
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:14
	qw422016.N().S(`
	metav1.ObjectMeta `)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:14
	qw422016.N().S("`")
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:14
	qw422016.N().S(`json:"metadata,omitempty"`)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:14
	qw422016.N().S("`")
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:14
	qw422016.N().S(`
}

func (h `)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:19
	qw422016.E().V(strcase.ToCamel(name))
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:19
	qw422016.N().S(`Chaos) DeepCopyObject() runtime.Object {
	panic("implement me")
}

// +kubebuilder:object:root=true

// `)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:25
	qw422016.E().V(strcase.ToCamel(name))
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:25
	qw422016.N().S(`ChaosList contains a list of `)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:25
	qw422016.E().V(strcase.ToCamel(name))
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:25
	qw422016.N().S(`Chaos
type `)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:26
	qw422016.E().V(strcase.ToCamel(name))
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:26
	qw422016.N().S(`ChaosList struct {
	metav1.TypeMeta `)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:26
	qw422016.N().S("`")
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:26
	qw422016.N().S(`json:",inline"`)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:26
	qw422016.N().S("`")
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:26
	qw422016.N().S(`
	metav1.ListMeta `)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:26
	qw422016.N().S("`")
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:26
	qw422016.N().S(`json:"metadata,omitempty"`)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:26
	qw422016.N().S("`")
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:26
	qw422016.N().S(`
	Items           []`)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:29
	qw422016.E().V(strcase.ToCamel(name))
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:29
	qw422016.N().S(`Chaos `)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:29
	qw422016.N().S("`")
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:29
	qw422016.N().S(`json:"items"`)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:29
	qw422016.N().S("`")
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:29
	qw422016.N().S(`
}

func (h `)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:32
	qw422016.E().V(strcase.ToCamel(name))
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:32
	qw422016.N().S(`ChaosList) DeepCopyObject() runtime.Object {
	panic("implement me")
}

func init() {
	SchemeBuilder.Register(&`)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:37
	qw422016.E().V(strcase.ToCamel(name))
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:37
	qw422016.N().S(`Chaos{}, &`)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:37
	qw422016.E().V(strcase.ToCamel(name))
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:37
	qw422016.N().S(`ChaosList{})
}
`)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:39
}

//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:39
func WriteChaosType(qq422016 qtio422016.Writer, name string) {
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:39
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:39
	StreamChaosType(qw422016, name)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:39
	qt422016.ReleaseWriter(qw422016)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:39
}

//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:39
func ChaosType(name string) string {
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:39
	qb422016 := qt422016.AcquireByteBuffer()
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:39
	WriteChaosType(qb422016, name)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:39
	qs422016 := string(qb422016.B)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:39
	qt422016.ReleaseByteBuffer(qb422016)
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:39
	return qs422016
//line template/chaos-mesh/api/v1alpha1/chaosType.qtpl:39
}
