// Code generated by qtc from "kustomization.yaml.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line template/chaos-mesh/config/crd/kustomization.yaml.qtpl:1
package crd

//line template/chaos-mesh/config/crd/kustomization.yaml.qtpl:1
import "github.com/iancoleman/strcase"

//line template/chaos-mesh/config/crd/kustomization.yaml.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template/chaos-mesh/config/crd/kustomization.yaml.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template/chaos-mesh/config/crd/kustomization.yaml.qtpl:2
func StreamKustomizationYaml(qw422016 *qt422016.Writer, name string) {
//line template/chaos-mesh/config/crd/kustomization.yaml.qtpl:2
	qw422016.N().S(`
# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/chaos-mesh.org_podchaos.yaml
- bases/chaos-mesh.org_networkchaos.yaml
- bases/chaos-mesh.org_iochaos.yaml
- bases/chaos-mesh.org_timechaos.yaml
- bases/chaos-mesh.org_kernelchaos.yaml
- bases/chaos-mesh.org_stresschaos.yaml
- bases/chaos-mesh.org_`)
//line template/chaos-mesh/config/crd/kustomization.yaml.qtpl:13
	qw422016.E().V(strcase.ToCamel(name))
//line template/chaos-mesh/config/crd/kustomization.yaml.qtpl:13
	qw422016.N().S(`chaos.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_podchaos.yaml
#- patches/webhook_in_networkchaos.yaml
#- patches/webhook_in_iochaos.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_podchaos.yaml
#- patches/cainjection_in_networkchaos.yaml
#- patches/cainjection_in_iochaos.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
`)
//line template/chaos-mesh/config/crd/kustomization.yaml.qtpl:34
}

//line template/chaos-mesh/config/crd/kustomization.yaml.qtpl:34
func WriteKustomizationYaml(qq422016 qtio422016.Writer, name string) {
//line template/chaos-mesh/config/crd/kustomization.yaml.qtpl:34
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/chaos-mesh/config/crd/kustomization.yaml.qtpl:34
	StreamKustomizationYaml(qw422016, name)
//line template/chaos-mesh/config/crd/kustomization.yaml.qtpl:34
	qt422016.ReleaseWriter(qw422016)
//line template/chaos-mesh/config/crd/kustomization.yaml.qtpl:34
}

//line template/chaos-mesh/config/crd/kustomization.yaml.qtpl:34
func KustomizationYaml(name string) string {
//line template/chaos-mesh/config/crd/kustomization.yaml.qtpl:34
	qb422016 := qt422016.AcquireByteBuffer()
//line template/chaos-mesh/config/crd/kustomization.yaml.qtpl:34
	WriteKustomizationYaml(qb422016, name)
//line template/chaos-mesh/config/crd/kustomization.yaml.qtpl:34
	qs422016 := string(qb422016.B)
//line template/chaos-mesh/config/crd/kustomization.yaml.qtpl:34
	qt422016.ReleaseByteBuffer(qb422016)
//line template/chaos-mesh/config/crd/kustomization.yaml.qtpl:34
	return qs422016
//line template/chaos-mesh/config/crd/kustomization.yaml.qtpl:34
}
